[pytest]
markers =
    smoke: marker for smoke tests
    regression: marker for regression tests
    need_review: marker for tests which should be reviewed
    login_guest: tests for guest users
    xfail: test which should fail